blank_issues_enabled: true
contact_links:
    - name: zksync-developers Discussion
      url: https://github.com/ZKsync-Community-Hub/zkync-developers/discussions
      about: Please provide feedback, and ask questions here.
    - name: ZKsync CLI documentation page
      about: Please refer to the documentation for immediate answers.      url: https://docs.zksync.io/build/zksync-cli
