name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Solidity
            directory: "templates/hardhat/solidity"
          - name: Vyper
            directory: "templates/hardhat/vyper"
          - name: 101
            directory: "templates/101"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies for ${{ matrix.name }}
        run: cd ${{ matrix.directory }} && yarn install --frozen-lockfile
      - name: Run ${{ matrix.name }} tests
        run: cd ${{ matrix.directory }} && yarn test
